spring:
  datasource:
    url: jdbc:mysql://sakuramiku.cn:13306/db_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: sakuramiku
    # 切换 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:cn.sakuramiku.demojdcloud.model
logging:
  level:
    cn.sakuramiku.demojdcloud.dao: debug
